- name: Build and Publish Dockerfile
  # You may pin to the exact commit or the version.
  # uses: ryanjfrizzell/action-bpd@7d6d0456081acbdbe2adeae5da1d14f1a0e54498
  uses: ryanjfrizzell/action-bpd@v1.0.2
  with:
    # the url your registry is located at, used for docker login, ex: docker.pkg.github.com
    docker_registry_url: # default is 
    # the owner for the registry, ex: ryanjfrizzell
    docker_registry_owner: # default is 
    # repository of the image, ex: action-bpd  
    docker_repository: # default is 
    # image name to use
    docker_image: # default is 
    # username needed to login to your registry
    docker_username: 
    # password needed to login to your registry
    docker_password: 
    # the location of your dockerfile
    dockerfile: # default is Dockerfile
    # the tag version you would like to use
    docker_image_tag: # default is latest
    # use this to override the formation of the image url
    docker_registry: # default is 
    # are you trying to push to dockerhub? [true/false]
    dockerhub: # default is false
